management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: ['configprops', 'env', 'health', 'info', 'logfile', 'loggers', 'prometheus', 'threaddump']

# SPRING CONFIGURATION
spring:
  application:
    name: image-object-detection-api
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
#  jpa:
#    open-in-view: false
#    pr